// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3heaIiH8Godhi6KKdfyYSVgHzyGQh8-o',
    appId: '1:458782984871:web:cc6c0e089adef86177a982',
    messagingSenderId: '458782984871',
    projectId: 'net-fusion-16728',
    authDomain: 'net-fusion-16728.firebaseapp.com',
    storageBucket: 'net-fusion-16728.appspot.com',
    measurementId: 'G-8XRR9MJNYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1HchpyrEaOQbzRKPhAXYaUq4jyLg22t0',
    appId: '1:458782984871:android:aa1edc66a1f2b9e177a982',
    messagingSenderId: '458782984871',
    projectId: 'net-fusion-16728',
    storageBucket: 'net-fusion-16728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilVtcWMktf2NLo0X4s8khD0tcX-5MsDM',
    appId: '1:458782984871:ios:5e8d0397c341719a77a982',
    messagingSenderId: '458782984871',
    projectId: 'net-fusion-16728',
    storageBucket: 'net-fusion-16728.appspot.com',
    iosBundleId: 'com.example.netfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilVtcWMktf2NLo0X4s8khD0tcX-5MsDM',
    appId: '1:458782984871:ios:69173b71c52c2cc677a982',
    messagingSenderId: '458782984871',
    projectId: 'net-fusion-16728',
    storageBucket: 'net-fusion-16728.appspot.com',
    iosBundleId: 'com.example.netfusion.RunnerTests',
  );
}
